// 추천 알고리즘을 바로 실행해 볼 수 있는 테스트용 장소 데이터입니다.
// Kakao Places 응답에는 평점/리뷰/혼잡도/현지인 리뷰 같은 값이 없을 수 있으므로,
// 실제 연동 시에는 서버 리뷰 데이터나 내부 로그 데이터와 병합해서 이 형태로 맞추면 됩니다.
export const mockRecommendationPlaces = [
  {
    id: "mock-001",
    name: "을지로 로컬 커피",
    category: "cafe",
    placeType: "indoor",
    tags: ["coffee", "quiet", "work"],
    lat: 37.5669,
    lng: 126.9911,
    distanceKm: 1.1,
    rating: 4.8,
    reviewCount: 184,
    localReviewCount: 121,
    crowdLevel: 0.32,
  },
  {
    id: "mock-002",
    name: "청계천 산책길",
    category: "park",
    placeType: "outdoor",
    tags: ["walk", "nature", "free"],
    lat: 37.5692,
    lng: 126.9788,
    distanceKm: 0.5,
    rating: 4.5,
    reviewCount: 98,
    localReviewCount: 77,
    crowdLevel: 0.58,
  },
  {
    id: "mock-003",
    name: "광화문 한식당",
    category: "food",
    placeType: "indoor",
    tags: ["meal", "korean", "group"],
    lat: 37.5716,
    lng: 126.9769,
    distanceKm: 0.8,
    rating: 4.6,
    reviewCount: 342,
    localReviewCount: 203,
    crowdLevel: 0.71,
  },
  {
    id: "mock-004",
    name: "서촌 책방",
    category: "culture",
    placeType: "indoor",
    tags: ["book", "quiet", "local"],
    lat: 37.5797,
    lng: 126.9705,
    distanceKm: 1.7,
    rating: 4.9,
    reviewCount: 64,
    localReviewCount: 55,
    crowdLevel: 0.24,
  },
  {
    id: "mock-005",
    name: "남산 전망 산책",
    category: "park",
    placeType: "outdoor",
    tags: ["view", "walk", "date"],
    lat: 37.5512,
    lng: 126.9882,
    distanceKm: 2.4,
    rating: 4.7,
    reviewCount: 410,
    localReviewCount: 188,
    crowdLevel: 0.84,
  },
  {
    id: "mock-006",
    name: "시청 앞 분식",
    category: "food",
    placeType: "indoor",
    tags: ["quick", "snack", "budget"],
    lat: 37.5648,
    lng: 126.9772,
    distanceKm: 0.3,
    rating: 4.2,
    reviewCount: 76,
    localReviewCount: 61,
    crowdLevel: 0.45,
  },
  {
    id: "mock-007",
    name: "정동 공연장",
    category: "culture",
    placeType: "indoor",
    tags: ["performance", "date", "evening"],
    lat: 37.5658,
    lng: 126.9738,
    distanceKm: 0.6,
    rating: 4.4,
    reviewCount: 133,
    localReviewCount: 66,
    crowdLevel: 0.51,
  },
  {
    id: "mock-008",
    name: "북촌 골목 산책",
    category: "culture",
    placeType: "outdoor",
    tags: ["walk", "photo", "history"],
    lat: 37.5826,
    lng: 126.9836,
    distanceKm: 2.0,
    rating: 4.6,
    reviewCount: 287,
    localReviewCount: 143,
    crowdLevel: 0.74,
  },
  {
    id: "mock-009",
    name: "종로 노포 국밥",
    category: "food",
    placeType: "indoor",
    tags: ["local", "meal", "korean"],
    lat: 37.5708,
    lng: 126.9852,
    distanceKm: 1.0,
    rating: 4.7,
    reviewCount: 221,
    localReviewCount: 180,
    crowdLevel: 0.62,
  },
  {
    id: "mock-010",
    name: "서울도서관",
    category: "culture",
    placeType: "indoor",
    tags: ["book", "quiet", "work"],
    lat: 37.5663,
    lng: 126.9785,
    distanceKm: 0.1,
    rating: 4.5,
    reviewCount: 156,
    localReviewCount: 101,
    crowdLevel: 0.36,
  },
  {
    id: "mock-011",
    name: "무교동 점심 골목",
    category: "food",
    placeType: "indoor",
    tags: ["meal", "quick", "office"],
    lat: 37.5671,
    lng: 126.9814,
    distanceKm: 0.4,
    rating: 4.3,
    reviewCount: 119,
    localReviewCount: 88,
    crowdLevel: 0.67,
  },
  {
    id: "mock-012",
    name: "덕수궁 돌담길",
    category: "park",
    placeType: "outdoor",
    tags: ["walk", "history", "date"],
    lat: 37.5659,
    lng: 126.9751,
    distanceKm: 0.4,
    rating: 4.8,
    reviewCount: 252,
    localReviewCount: 176,
    crowdLevel: 0.49,
  },
];

export const mockRecommendationContext = {
  userLocation: { lat: 37.5665, lng: 126.978 },
  userPreference: {
    categories: ["cafe", "culture"],
    tags: ["quiet", "book", "work"],
  },
  weather: {
    condition: "rain",
    temperature: 21,
    precipitationProbability: 0.7,
  },
  currentTime: "15:30",
};
